services:
  postgres:
    image: postgres:17-alpine
    container_name: bank-db
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank -d bankdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bank_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bank-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bank.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bank_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bankdb
      SPRING_DATASOURCE_USERNAME: bank
      SPRING_DATASOURCE_PASSWORD: bank
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bank_network

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: bank-jenkins
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - bank_network

volumes:
  postgres_data:
  jenkins_home:

networks:
  bank_network:
    driver: bridge