spring:
  application:
    name: accounting-service
  datasource:
    url: jdbc:postgresql://localhost:5432/accountingdb
    username: accounting
    password: accounting
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration

server:
  port: 8080