spring:
  application:
    name: accounting-service
  datasource:
    url: jdbc:postgresql://localhost:5433/accounting_test_db
    username: test
    password: test
  flyway:
    enabled: true
    locations: classpath:db/migration